/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votingapp;

import java.awt.event.ActionListener;
import javax.swing.Timer;
import org.apache.log4j.Logger;

/**
 *
 * @author wolfpack
 */
public class votingWindow extends javax.swing.JFrame {

    /**
     * Creates new form votingWindow
     */
    static String team1 ="Team Number 1";
    static String team2 ="Team Number 2";
    static String team3 ="Team Number 3";
    static String team4 ="Team Number 4";
    static String team5 ="Team Number 5";
    
    int timeLimit=100000000; // delay for about 3 seconds
    
    static int vote1=0;
    static int vote2=0;
    static int vote3=0;
    static int vote4=0;
    static int vote5=0;
    
    final static Logger logger = Logger.getLogger(votingWindow.class);
    
        
    public votingWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVote01 = new javax.swing.JButton();
        btnVote02 = new javax.swing.JButton();
        btnVote03 = new javax.swing.JButton();
        btnVote04 = new javax.swing.JButton();
        btnVote05 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVote01.setBackground(java.awt.Color.gray);
        btnVote01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png"))); // NOI18N
        btnVote01.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVote01.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVote01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVote01MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVote01MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVote01MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVote01MouseEntered(evt);
            }
        });
        btnVote01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote01ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVote01, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 232, 131));

        btnVote02.setBackground(java.awt.Color.gray);
        btnVote02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png"))); // NOI18N
        btnVote02.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVote02.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVote02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVote02MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVote02MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVote02MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVote02MouseEntered(evt);
            }
        });
        btnVote02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote02ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVote02, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 150, 232, 131));

        btnVote03.setBackground(java.awt.Color.gray);
        btnVote03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png"))); // NOI18N
        btnVote03.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVote03.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVote03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVote03MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVote03MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVote03MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVote03MouseEntered(evt);
            }
        });
        btnVote03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote03ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVote03, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 290, 232, 131));

        btnVote04.setBackground(java.awt.Color.gray);
        btnVote04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png"))); // NOI18N
        btnVote04.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVote04.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVote04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVote04MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVote04MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVote04MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVote04MouseEntered(evt);
            }
        });
        btnVote04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote04ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVote04, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 430, 232, 131));

        btnVote05.setBackground(java.awt.Color.gray);
        btnVote05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png"))); // NOI18N
        btnVote05.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVote05.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVote05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVote05MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnVote05MouseReleased(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVote05MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVote05MouseEntered(evt);
            }
        });
        btnVote05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVote05ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVote05, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 570, 232, 131));

        jLabel6.setFont(new java.awt.Font("Abyssinica SIL", 1, 60)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(team5);
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 1030, 130));

        jLabel5.setFont(new java.awt.Font("Abyssinica SIL", 1, 60)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(team4);
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 1030, 130));

        jLabel4.setFont(new java.awt.Font("Abyssinica SIL", 1, 60)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(team3);
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 1030, 130));

        jLabel3.setFont(new java.awt.Font("Abyssinica SIL", 1, 60)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(team2);
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 1030, 130));

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 1, 60)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(team1);
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 1030, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jLabel1.setBorder(null);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVote02MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote02MousePressed
        btnVote02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark.png")));// TODO add your handling code here:
        jLabel3.setText("Your vote has been counted");
        btnVote02.setEnabled(false);
    }//GEN-LAST:event_btnVote02MousePressed

    private void btnVote02MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote02MouseReleased
        btnVote02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png")));
        int i;
        for(i=0;i<timeLimit;i++){
            jLabel3.setText(team2);
        }
        vote2++;
        logger.info("A vote for "+team2);
        btnVote02.setEnabled(true);
    }//GEN-LAST:event_btnVote02MouseReleased

    private void btnVote02MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote02MouseExited
        btnVote02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png")));
    }//GEN-LAST:event_btnVote02MouseExited

    private void btnVote02MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote02MouseEntered
        btnVote02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/light.png")));
    }//GEN-LAST:event_btnVote02MouseEntered

    private void btnVote02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote02ActionPerformed

    }//GEN-LAST:event_btnVote02ActionPerformed

    private void btnVote05MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote05MousePressed
        btnVote05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark.png")));
        jLabel6.setText("Your vote has been counted");
        btnVote05.setEnabled(false);
    }//GEN-LAST:event_btnVote05MousePressed

    private void btnVote05MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote05MouseReleased
        btnVote05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png")));
        int i;
        for(i=0;i<timeLimit;i++){
            jLabel6.setText(team5);
        }
        vote5++;
        logger.info("A vote for "+team5);
        btnVote05.setEnabled(true);
    }//GEN-LAST:event_btnVote05MouseReleased

    private void btnVote05MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote05MouseExited
        btnVote05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png")));
    }//GEN-LAST:event_btnVote05MouseExited

    private void btnVote05MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote05MouseEntered
        btnVote05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/light.png")));
    }//GEN-LAST:event_btnVote05MouseEntered

    private void btnVote05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote05ActionPerformed
        
    }//GEN-LAST:event_btnVote05ActionPerformed

    private void btnVote03MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote03MousePressed
        btnVote03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark.png")));
        jLabel4.setText("Your vote has been counted");
        btnVote03.setEnabled(false);
    }//GEN-LAST:event_btnVote03MousePressed

    private void btnVote03MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote03MouseReleased
        btnVote03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png")));
        int i;
        for(i=0;i<timeLimit;i++){
            jLabel4.setText(team3);
        }
        vote3++;
        logger.info("A vote for "+team3);
        btnVote03.setEnabled(true);
    }//GEN-LAST:event_btnVote03MouseReleased

    private void btnVote03MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote03MouseExited
        btnVote03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png")));
    }//GEN-LAST:event_btnVote03MouseExited

    private void btnVote03MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote03MouseEntered
        btnVote03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/light.png")));
    }//GEN-LAST:event_btnVote03MouseEntered

    private void btnVote03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVote03ActionPerformed

    private void btnVote01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote01MousePressed
        btnVote01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark.png")));
        jLabel2.setText("Your vote has been counted");
        btnVote01.setEnabled(false);
        
        
        
    }//GEN-LAST:event_btnVote01MousePressed

    private void btnVote01MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote01MouseReleased
        btnVote01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png")));
        int i;
        for(i=0;i<timeLimit;i++){
            jLabel2.setText(team1);
        }
        vote1++;
        logger.info("A vote for "+team1);
        btnVote01.setEnabled(true);
        
        
    }//GEN-LAST:event_btnVote01MouseReleased

    private void btnVote01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote01MouseExited
        btnVote01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png")));
    }//GEN-LAST:event_btnVote01MouseExited

    private void btnVote01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote01MouseEntered
        btnVote01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/light.png")));
    }//GEN-LAST:event_btnVote01MouseEntered

    private void btnVote01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote01ActionPerformed
          
    }//GEN-LAST:event_btnVote01ActionPerformed

    private void btnVote04MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote04MousePressed
        btnVote04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dark.png")));
        jLabel5.setText("Your vote has been counted");
        btnVote04.setEnabled(false);
    }//GEN-LAST:event_btnVote04MousePressed

    private void btnVote04MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote04MouseReleased
        btnVote04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png")));
        int i;
        for(i=0;i<timeLimit;i++){
            jLabel5.setText(team4);
        }
        vote4++;
        logger.info("A vote for "+team4);
        btnVote04.setEnabled(true);
        
    }//GEN-LAST:event_btnVote04MouseReleased

    private void btnVote04MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote04MouseExited
        btnVote04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png")));
    }//GEN-LAST:event_btnVote04MouseExited

    private void btnVote04MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVote04MouseEntered
        btnVote04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/light.png")));
    }//GEN-LAST:event_btnVote04MouseEntered

    private void btnVote04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVote04ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVote04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(votingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(votingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(votingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(votingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new votingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVote01;
    private javax.swing.JButton btnVote02;
    private javax.swing.JButton btnVote03;
    private javax.swing.JButton btnVote04;
    private javax.swing.JButton btnVote05;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
